import {test,expect,_electron as electron} from '@playwright/test'
import fs from 'node:fs/promises'
import path from 'node:path'
import os from 'node:os'
const source=process.env.THUS_REFERENCE_ROOT
const mod=process.platform==='darwin'?'Meta':'Control'
test('desktop writing, preview, metadata, save conflict, search and recovery',async()=>{
  const root=await fs.mkdtemp(path.join(os.tmpdir(),'thus-e2e-'));const project=path.join(root,'project');const posts=path.join(project,'content/posts/2026/09/20');const profile=path.join(root,'profile')
  await fs.mkdir(posts,{recursive:true});await fs.mkdir(path.join(project,'.vitepress'));await fs.mkdir(path.join(project,'src/styles'),{recursive:true})
  await fs.writeFile(path.join(project,'.vitepress/config.ts'),"// github-light github-dark\nthrow new Error('Do not execute')")
  for(const file of ['theme.css','markdown.css'])await fs.writeFile(path.join(project,'src/styles',file),source?await fs.readFile(path.join(source,'src/styles',file),'utf8'):':root{--accent:#2f6f61}.markdown-body{line-height:1.85}')
  if(source){await fs.mkdir(path.join(project,'content/public/icons'),{recursive:true});await fs.copyFile(path.join(source,'content/public/icons/copy.svg'),path.join(project,'content/public/icons/copy.svg'))}
  const first='---\ntitle: 写作测试\ndescription: 用熟悉的 Markdown 记录想法。\ntags: [写作, 设计]\ndraft: true\n# keep this comment\ncustom: retained\n---\n# 写作测试\n\n## 一个安静的地方\n\n原始正文。\n\n::: tip 提示\n==高亮== H~2~O x^2^ :smile:\n:::\n\n$$\nx^2 + y^2 = z^2\n$$\n\n```mermaid\ngraph LR\nA[写作] --> B[预览]\n```\n\n::: code-group\n\n```js [first]\nconst x = 1\n```\n\n```ts [second]\nconst y: number = 2\n```\n\n:::\n\n<script>window.__unsafe = true</script>\n'
  await fs.writeFile(path.join(posts,'first.md'),first);await fs.writeFile(path.join(posts,'second.md'),'---\ntitle: 另一篇文章\ntags: [生活]\n---\n# 另一篇文章\n\n内容')
  const env:Record<string,string>=Object.fromEntries(Object.entries({...process.env,THUS_USER_DATA:profile,THUS_DISABLE_WATCHER:'1',THUS_DISABLE_UPDATE_CHECK:'1'}).filter((entry):entry is [string,string]=>typeof entry[1]==='string'));delete env.ELECTRON_RUN_AS_NODE
  const app=await electron.launch({args:['.'],env});const page=await app.firstWindow();const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')console.log('browser:',m.text())})
  try{
    await page.getByRole('button',{name:'也可以粘贴项目的绝对路径。'}).click();await page.getByLabel('项目目录',{exact:true}).fill(project);await page.getByRole('button',{name:'连接目录',exact:true}).click();await page.getByRole('button',{name:'进入写作空间'}).click();await expect(page.locator('.article-row')).toHaveCount(2)
    await page.locator('.article-row').filter({hasText:'写作测试'}).dblclick();await expect(page.locator('.cm-editor')).toBeVisible()
    const preview=page.frameLocator('iframe');await expect(preview.locator('h1')).toHaveText('写作测试');await expect(preview.locator('mjx-container')).toHaveCount(1);await expect(preview.locator('.mermaid-output svg')).toHaveCount(1);await expect(preview.locator('.mermaid-output')).toContainText('写作');await expect(preview.locator('.custom-block')).toContainText('高亮');await expect(preview.locator('script')).toHaveCount(1)
    const secondTab=preview.locator('.vp-code-group label').filter({hasText:'second'});await secondTab.evaluate((label:HTMLLabelElement)=>label.click());await expect(preview.locator('.blocks > .active')).toContainText('const y')
    await page.locator('.cm-content').click();await page.keyboard.press(mod+'+End');await page.keyboard.type('\n\nSaved from editor.');await expect(page.locator('.statusbar')).toContainText('有未保存修改');await page.getByRole('button',{name:'保存',exact:true}).click();await expect(page.locator('.statusbar')).toContainText('已保存到本地');expect(await fs.readFile(path.join(posts,'first.md'),'utf8')).toContain('Saved from editor.')
    await page.locator('.toolbar').getByRole('button',{name:'文章信息',exact:true}).click();await page.getByLabel('标题',{exact:true}).fill('更新后的标题');await page.getByRole('button',{name:'应用修改'}).click();await page.getByRole('button',{name:'保存',exact:true}).click();await expect(page.locator('.statusbar')).toContainText('已保存到本地');const saved=await fs.readFile(path.join(posts,'first.md'),'utf8');expect(saved).toContain('# keep this comment');expect(saved).toContain('custom: retained')
    await page.screenshot({path:'test-results/editor-light.png'})
    await page.getByRole('button',{name:'项目设置',exact:true}).click();await page.getByRole('button',{name:'外观与写作',exact:true}).click();await page.getByRole('button',{name:'深色',exact:true}).click();await expect(page.locator('html')).toHaveClass('dark');await page.getByRole('button',{name:'返回写作',exact:true}).click();await page.screenshot({path:'test-results/editor-dark.png'})
    await page.locator('.cm-content').click();await page.keyboard.press(mod+'+End');await page.keyboard.type('\nLocal unsaved.');await fs.writeFile(path.join(posts,'first.md'),saved+'\nExternal change.');await app.evaluate(({BrowserWindow},file)=>BrowserWindow.getAllWindows()[0].webContents.send('project:change',{kind:'content',file}),'posts/2026/09/20/first.md');await expect(page.getByRole('dialog')).toContainText('文件已在其他程序中修改');await expect(page.locator('.comparison')).toContainText('Local unsaved.');await page.getByRole('button',{name:'取消',exact:true}).click()
    await page.keyboard.press(mod+'+p');await page.getByLabel('快速查找').fill('另一篇');await page.getByLabel('快速查找').press('Enter');await expect(page.getByRole('dialog')).toContainText('保存修改后再离开');await page.getByRole('button',{name:'放弃修改',exact:true}).click();await expect(page.locator('.editor-heading h1')).toHaveText('另一篇文章');expect(await fs.readFile(path.join(posts,'first.md'),'utf8')).toContain('External change.')
    await page.getByRole('button',{name:'项目设置',exact:true}).click();await page.getByRole('button',{name:'项目',exact:true}).click();await page.getByRole('button',{name:'恢复副本',exact:true}).click();await expect(page.getByRole('dialog')).toContainText('first.md');await page.getByRole('button',{name:'恢复',exact:true}).click();await expect(page.locator('.cm-content')).toContainText('Local unsaved.');await expect(page.locator('.statusbar')).toContainText('有未保存修改')
    await page.getByRole('button',{name:'＋ 新建文章'}).click();await page.getByRole('button',{name:'放弃修改',exact:true}).click();await page.getByLabel('标题',{exact:true}).fill('新建的文章');await page.getByLabel('文件名',{exact:true}).fill('new-article');await page.getByLabel('发布日期',{exact:true}).fill('2026-09-20');await page.getByRole('button',{name:'创建草稿',exact:true}).click();await expect(page.locator('.editor-heading h1')).toHaveText('新建的文章');expect(await fs.readFile(path.join(posts,'new-article.md'),'utf8')).toContain('draft: true')
    const image=path.join(root,'test.png');await fs.writeFile(image,Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jX1sAAAAASUVORK5CYII=','base64'));await app.evaluate(({dialog},file)=>{(dialog as any).showOpenDialog=async()=>({canceled:false,filePaths:[file]})},image)
    await page.getByRole('button',{name:'插入图片',exact:true}).click();await page.getByLabel('替代文字',{exact:true}).fill('测试图片');await page.getByRole('button',{name:'复制并插入',exact:true}).click();await expect(preview.locator('img[alt="测试图片"]')).toHaveCount(1);expect(await fs.readFile(path.join(posts,'assets/test.png'))).toEqual(await fs.readFile(image));await page.getByRole('button',{name:'保存',exact:true}).click();await expect(page.locator('.statusbar')).toContainText('已保存到本地')
    await page.getByRole('button',{name:'更多文章操作'}).click();await page.getByRole('button',{name:'移动或重命名',exact:true}).click();await page.getByLabel('文件名',{exact:true}).fill('renamed');await page.getByLabel('发布日期',{exact:true}).fill('2026-09-21');await page.getByRole('button',{name:'检查移动影响'}).click();await page.getByRole('button',{name:'确认移动',exact:true}).click();await expect(page.locator('.breadcrumb')).toContainText('2026/09/21/renamed.md');expect(await fs.readFile(path.join(project,'content/posts/2026/09/21/renamed.md'),'utf8')).toContain('../20/assets/test.png')
    await page.getByRole('button',{name:/全部文章/}).click();await page.getByLabel('搜索文章').fill('新建的');await expect(page.locator('.article-row')).toHaveCount(1);await page.screenshot({path:'test-results/library.png'})
    expect(errors).toEqual([])
  }catch(error){console.log('PAGE ERRORS',errors);console.log('PAGE',await page.locator('body').innerText());console.log('FRAMES',page.frames().map(f=>f.url()));await page.screenshot({path:'test-results/failure.png'});throw error}finally{const closed=app.waitForEvent('close');await app.evaluate(({app})=>app.exit());await closed;await fs.rm(root,{recursive:true,force:true,maxRetries:10,retryDelay:200})}
})
