<script setup lang="ts">
import { ref,computed,watch,onMounted,onBeforeUnmount,nextTick } from 'vue'
import Editor from './Editor.vue'
import Modal from './Modal.vue'
import BlogSettings from './BlogSettings.vue'
import WindowBar from './WindowBar.vue'
import { frontmatter,updateMetadata } from '../shared/frontmatter'
import type { Project,Post,DocumentFile,RenderResult,Recovery,MovePlan,Preferences } from '../shared/types'

const bridge=window.editor
const api:typeof bridge=bridge&&{...bridge,invoke<T=any>(action:string,payload?:any){return bridge.invoke<T>(action,payload===undefined?undefined:JSON.parse(JSON.stringify(payload)))}}
const project=ref<Project>();const pathInput=ref('');const connecting=ref(false);const checked=ref(false);const connectError=ref('')
const view=ref<'library'|'write'|'settings'|'blog'>('library');const category=ref('all');const query=ref('');const search=ref('');const composing=ref(false)
const blogSettings=ref<InstanceType<typeof BlogSettings>>();
const settingsTab=ref('project');const tagQuery=ref('');const pathExpanded=ref(false)
const year=ref('');const month=ref('');const tags=ref<string[]>([]);const sort=ref('modified');const selected=ref<Post>();const listTop=ref(0)
const filterYear=ref(''),filterMonth=ref(''),filterTags=ref<string[]>([])
const opened=ref<DocumentFile>();const raw=ref('');const savedRaw=ref('');const saving=ref(false);const saveError=ref('');const notice=ref('')
const mode=ref<'write'|'split'|'preview'>('split');const fullSource=ref(false);const renderResult=ref<RenderResult>();const renderError=ref('');const rendering=ref(false)
const modal=ref('');const modalError=ref('');const pendingAction=ref<(()=>Promise<void>)|null>(null);const quickQuery=ref('');const quickIndex=ref(0)
const preferences=ref<Preferences>({theme:'system',syncScroll:true,split:50});const systemDark=ref(matchMedia('(prefers-color-scheme: dark)').matches);const fontSize=ref(14)
const dark=computed(()=>preferences.value.theme==='dark'||(preferences.value.theme!=='light'&&systemDark.value));const modifier=api?.platform==='darwin'?'⌘':'Ctrl'
const editor=ref<InstanceType<typeof Editor>>();const preview=ref<HTMLIFrameElement>();const previewReady=ref(false);const listScroller=ref<HTMLElement>()
const editorText=computed({get(){if(fullSource.value)return raw.value;try{return frontmatter(raw.value).body}catch{return raw.value}},set(value:string){if(fullSource.value){raw.value=value;return}try{raw.value=frontmatter(raw.value).prefix+value}catch{raw.value=value}}})
const metadata=computed(()=>{try{return frontmatter(raw.value).data}catch{return {}}});const yamlError=computed(()=>{try{frontmatter(raw.value);return ''}catch(e:any){return e.message}})
const isHome=computed(()=>opened.value?.file==='index.md');
const dirty=computed(()=>!!opened.value&&raw.value!==savedRaw.value)
const posts=computed(()=>project.value?.posts||[])
const filtered=computed(()=>posts.value.filter(p=>{
  const q=search.value.toLocaleLowerCase();return (category.value!=='drafts'||p.draft)&&(!year.value||p.date.startsWith(year.value))&&(!month.value||p.date.slice(5,7)===month.value)&&(!tags.value.length||p.tags.some(t=>tags.value.includes(t)))&&(!q||[p.title,p.file,...p.tags].join(' ').toLocaleLowerCase().includes(q))
}).sort((a,b)=>(sort.value==='date'?b.date.localeCompare(a.date):b.modified-a.modified)||a.file.localeCompare(b.file)))
const years=computed(()=>[...new Set(posts.value.map(p=>p.date.slice(0,4)).filter(Boolean))].sort().reverse())
const allTags=computed(()=>[...new Set(posts.value.flatMap(p=>p.tags))].sort())
const rowStride=128
const virtualStart=computed(()=>Math.max(0,Math.floor(listTop.value/rowStride)-3));const visiblePosts=computed(()=>filtered.value.slice(virtualStart.value,virtualStart.value+16))
const quickResults=computed(()=>posts.value.filter(p=>[p.title,p.file,...p.tags].join(' ').toLowerCase().includes(quickQuery.value.toLowerCase())).slice(0,40))
const currentPost=computed(()=>posts.value.find(p=>p.file===opened.value?.file));const activeTitle=computed(()=>metadata.value.title||currentPost.value?.title||(isHome.value?'首页':'未命名文章'))
const plannedImage=ref<{existing:boolean;original:string;suggested:string}>()
const forms=ref<any>({});const recoveries=ref<Recovery[]>([]);const movePlan=ref<MovePlan>();const disk=ref<DocumentFile>();const imageData=ref<{name:string;bytes:number[];alt:string;replace?:string}>()
const overviewPreview=ref<HTMLIFrameElement>();const overviewResult=ref<RenderResult>();const overviewError=ref('');const overviewLoading=ref(false)
let overviewToken=0
async function renderOverview(){
  const post=selected.value;const token=++overviewToken;overviewResult.value=undefined;overviewError.value=''
  if(!post||view.value!=='library')return
  overviewLoading.value=true
  try{const doc=await api.invoke<DocumentFile>('read',{file:post.file});if(token!==overviewToken)return;const result=await api.invoke<RenderResult>('render',{raw:doc.raw,file:doc.file});if(token!==overviewToken)return;overviewResult.value=result;sendOverview()}
  catch(e:any){if(token===overviewToken)overviewError.value=e.message}
  finally{if(token===overviewToken)overviewLoading.value=false}
}
function sendOverview(){if(overviewResult.value&&selected.value)overviewPreview.value?.contentWindow?.postMessage({type:'render',single:true,id:overviewToken,result:JSON.parse(JSON.stringify(overviewResult.value)),styles:project.value?.styles,file:selected.value.file,date:selected.value.date,draft:selected.value.draft,dark:dark.value,degraded:!!project.value?.warnings.length,readOnly:true},'*')}
watch([()=>selected.value?.file,()=>selected.value?.modified,view],()=>void renderOverview())
watch(filtered,items=>{selected.value=items.find(p=>p.file===selected.value?.file)||items[0]})
let renderToken=0,documentToken=0;let searchTimer:ReturnType<typeof setTimeout>,renderTimer:ReturnType<typeof setTimeout>,recoveryTimer:ReturnType<typeof setTimeout>,noticeTimer:ReturnType<typeof setTimeout>
let stopChange:()=>void,stopClose:()=>void;let lastScrollLine=1
function toast(message:string){notice.value=message;clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>notice.value='',4500)}
function openModal(name:string){if(name==='date'||name==='tags'){filterYear.value=year.value;filterMonth.value=month.value;filterTags.value=[...tags.value]}modalError.value='';modal.value=name}
function closeModal(){if(saving.value&&['unsaved','conflict','saveError'].includes(modal.value))return;modal.value='';modalError.value='';pendingAction.value=null}
async function applyFilters(){const nextYear=filterYear.value,nextMonth=filterMonth.value,nextTags=[...filterTags.value];const kind=modal.value;closeModal();await nextTick();if(kind==='date'){year.value=nextYear;await nextTick();month.value=nextMonth}else if(kind==='tags')tags.value=nextTags;listTop.value=0;if(listScroller.value)listScroller.value.scrollTop=0}
async function protect(fn:()=>Promise<void>){if(blogSettings.value&&!await blogSettings.value.confirmLeave())return;if(dirty.value){pendingAction.value=fn;openModal('unsaved')}else await fn()}
async function persistRecovery(){if(opened.value&&dirty.value)await api.invoke('recovery',{file:opened.value.file,raw:raw.value,hash:opened.value.hash})}
async function refresh(){if(project.value)project.value=await api.invoke<Project>('refresh')}
async function connect(){connecting.value=true;connectError.value='';try{project.value=await api.invoke('connect',{root:pathInput.value.trim()});checked.value=true;recoveries.value=await api.invoke('recoveries')}catch(e:any){connectError.value=e.message}finally{connecting.value=false}}
async function chooseFolder(){try{const folder=await api.invoke<string|null>('chooseProject');if(folder){pathInput.value=folder;await connect()}}catch(e:any){connectError.value=e.message}}
function enter(){checked.value=false;view.value='library';const l=preferences.value.library;if(l){category.value=l.category==='drafts'?'drafts':'all';query.value=l.query;search.value=l.query;year.value=l.year;nextTick(()=>month.value=l.month);tags.value=l.tags;sort.value=l.sort;selected.value=posts.value.find(p=>p.file===l.selected);listTop.value=l.scroll;nextTick(()=>{if(listScroller.value)listScroller.value.scrollTop=l.scroll})}if(!selected.value)selected.value=filtered.value[0];if(recoveries.value.length)openModal('recovery')}
const connected=computed(()=>!!project.value&&!checked.value)
async function load(post:Post|string,writing=true){await protect(async()=>{
  const file=typeof post==='string'?post:post.file;const token=++documentToken
  try{const doc=await api.invoke<DocumentFile>('read',{file});if(token!==documentToken)return;clearTimeout(recoveryTimer);opened.value=doc;raw.value=doc.raw;savedRaw.value=doc.raw;selected.value=posts.value.find(p=>p.file===file);saveError.value='';fullSource.value=false;renderResult.value=undefined;renderError.value='';if(writing)view.value='write';modal.value='';await nextTick();scheduleRender()}catch(e:any){toast(e.message)}
})}
async function save(){if(!opened.value||saving.value)return false;const captured=raw.value;const file=opened.value.file;const token=documentToken;saving.value=true;saveError.value=''
  try{const result=await api.invoke<DocumentFile>('save',{file,raw:captured,hash:opened.value.hash});if(token===documentToken){opened.value=result;savedRaw.value=captured;if(raw.value===captured)await api.invoke('discardRecovery',{file});else await persistRecovery()}await refresh();toast('已保存到本地');return true}
  catch(e:any){saveError.value=e.message;await persistRecovery().catch(()=>{});if(e.message.includes('CONFLICT')){try{disk.value=await api.invoke('read',{file})}catch{}openModal('conflict')}else openModal('saveError');return false}
  finally{saving.value=false}
}
async function continueUnsaved(discard=false){const fn=pendingAction.value;if(!fn)return;if(!discard&&(!(await save())||dirty.value))return;if(discard){await persistRecovery();raw.value=savedRaw.value}modal.value='';pendingAction.value=null;await fn()}
async function saveAs(){try{const location=await api.invoke('saveAs',{file:opened.value?.file||'recovered.md',raw:raw.value});if(location)toast('已另存副本：'+location)}catch(e:any){modalError.value=e.message}}
async function reloadDisk(){try{await persistRecovery();const doc=await api.invoke<DocumentFile>('read',{file:opened.value!.file});opened.value=doc;raw.value=doc.raw;savedRaw.value=doc.raw;modal.value='';saveError.value='';toast('已加载磁盘内容，之前的修改保留在恢复副本中')}catch(e:any){modalError.value=e.message}}
function navigate(name:string){void protect(async()=>{view.value='library';category.value=name;query.value='';search.value='';year.value='';month.value='';tags.value=[];listTop.value=0})}
function scheduleRender(){clearTimeout(renderTimer);renderTimer=setTimeout(runRender,250)}
async function runRender(){if(!opened.value)return;const token=++renderToken;rendering.value=true;try{const result=await api.invoke<RenderResult>('render',{raw:raw.value,file:opened.value.file});if(token!==renderToken)return;renderResult.value=result;renderError.value='';sendPreview()}catch(e:any){if(token===renderToken)renderError.value=e.message}finally{if(token===renderToken)rendering.value=false}}
function sendPreview(){if(!previewReady.value||!renderResult.value||!opened.value)return;preview.value?.contentWindow?.postMessage({type:'render',single:mode.value==='preview',id:renderToken,result:JSON.parse(JSON.stringify(renderResult.value)),styles:project.value?.styles,file:opened.value.file,date:currentPost.value?.date||'',draft:metadata.value.draft===true,dark:dark.value,degraded:!!project.value?.warnings.length},'*')}
function onEditorScroll(line:number){if(!preferences.value.syncScroll)return;let offset=0;try{offset=fullSource.value?0:frontmatter(raw.value).offset}catch{}lastScrollLine=line+offset;preview.value?.contentWindow?.postMessage({type:'scroll',line:lastScrollLine},'*')}
async function onMessage(event:MessageEvent){
  if(event.source===overviewPreview.value?.contentWindow){
    if(event.data.type==='ready')sendOverview()
    if(event.data.type==='copy')await navigator.clipboard.writeText(String(event.data.text)).catch(()=>toast('复制失败'))
    if(event.data.type==='link'&&/^https?:\/\//.test(event.data.href)){forms.value={url:event.data.href};openModal('external')}
    return
  }
  if(event.source!==preview.value?.contentWindow)return;const data=event.data
  if(data.type==='ready'){previewReady.value=true;sendPreview()}
  if(data.type==='copy')await navigator.clipboard.writeText(String(data.text)).catch(()=>toast('复制失败'))
  if(data.type==='replaceImage')await chooseImage(data.src)
  if(data.type==='scroll'&&preferences.value.syncScroll){let offset=0;try{offset=fullSource.value?0:frontmatter(raw.value).offset}catch{}editor.value?.scrollTo(data.line-offset)}
  if(data.type==='link'){
    if(isHome.value&&data.href==='/blog'){navigate('all');return}
    if(data.href==='/'||data.href==='/index.md'){await load('index.md');return}
    if(/^https?:\/\//.test(data.href)){forms.value={url:data.href};openModal('external');return}
    const parts=(data.href.startsWith('/')?data.href.slice(1):opened.value!.file.split('/').slice(0,-1).join('/')+'/'+data.href).split('/');const stack:string[]=[];for(const part of parts){if(part==='..')stack.pop();else if(part!=='.')stack.push(part)}
    const target=decodeURIComponent(stack.join('/').split(/[?#]/)[0]).replace(/\.md$/,'').replace(/\/index$/,'').replace(/\/$/,'');const post=posts.value.find(p=>p.file.replace(/\.md$/,'').replace(/\/index$/,'')===target);if(post)await load(post);else toast('未找到对应文章：'+data.href)
  }
}
function showNew(){forms.value={title:'',slug:'',date:new Date().toLocaleDateString('en-CA'),folder:false};openModal('new')}
async function createPost(){try{if(!forms.value.title.trim())throw new Error('请输入标题');const content=updateMetadata('',{title:forms.value.title.trim(),description:'',tags:[],draft:true})+'\n';const doc=await api.invoke<DocumentFile>('create',{...forms.value,raw:content});await refresh();modal.value='';await load(doc.file)}catch(e:any){modalError.value=e.message}}
function showMetadata(){if(yamlError.value){fullSource.value=true;openModal('yaml');return}forms.value={title:metadata.value.title||activeTitle.value,description:metadata.value.description||'',tags:(metadata.value.tags||[]).join(', '),draft:metadata.value.draft===true,updated:metadata.value.updated||''};openModal('metadata')}
function applyMetadata(confirmed=false){try{if(!forms.value.title.trim())throw new Error('请输入标题');if(forms.value.updated&&(!/^\d{4}-\d{2}-\d{2}$/.test(forms.value.updated)||!Number.isFinite(Date.parse(forms.value.updated))||new Date(forms.value.updated).toISOString().slice(0,10)!==forms.value.updated||forms.value.updated<(currentPost.value?.date||'')))throw new Error('更新日期必须有效，且不能早于发布日期');if(metadata.value.draft===true&&!forms.value.draft&&!confirmed){openModal('publish');return}raw.value=updateMetadata(raw.value,{...forms.value,tags:[...new Set(String(forms.value.tags).split(/[,，]/).map(t=>t.trim()).filter(Boolean))]});closeModal()}catch(e:any){modalError.value=e.message}}
async function chooseImage(replace?:string){try{const image=await api.invoke<{name:string;bytes:Uint8Array}|null>('chooseImage');if(image){imageData.value={name:image.name,bytes:Array.from(image.bytes),alt:'',replace};openModal('image')}}catch(e:any){toast(e.message)}}
async function droppedImage(file:File){if(file.size>25*1024*1024){toast('图片不能超过 25 MB');return}imageData.value={name:file.name||'image.png',bytes:Array.from(new Uint8Array(await file.arrayBuffer())),alt:''};openModal('image')}
async function insertImage(useExisting=false,confirmed=false){if(!imageData.value||!opened.value)return;try{const image=imageData.value;if(!confirmed){plannedImage.value=await api.invoke('imagePlan',{file:opened.value.file,name:image.name});if(plannedImage.value?.existing){openModal('imageConflict');return}}const result=await api.invoke('importImage',{file:opened.value.file,...image,useExisting});const ref=result.relative.split('/').map(encodeURIComponent).join('/');if(image.replace)raw.value=raw.value.replace(image.replace,ref);else editor.value?.insert(`![${image.alt.replace(/[\[\]\n]/g,'')}](${ref})`);closeModal();toast(result.existing?'已引用现有图片':'图片已复制，正文尚未保存')}catch(e:any){modalError.value=e.message}}
function showMove(){forms.value={slug:opened.value!.file.replace(/\/index\.md$/,'').split('/').at(-1)!.replace(/\.md$/,''),date:currentPost.value?.date||'',folder:opened.value!.file.endsWith('/index.md')};openModal('move')}
async function planMove(){try{if(dirty.value)throw new Error('请先保存当前修改，再移动文章');const {date,slug,folder}=forms.value;if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||!Number.isFinite(Date.parse(date))||new Date(date).toISOString().slice(0,10)!==date||!/^[\p{L}\p{N}][\p{L}\p{N}_-]*$/u.test(slug))throw new Error('请输入有效日期和文件名');const to=`posts/${date.replaceAll('-','/')}/${slug}${folder?'/index':''}.md`;movePlan.value=await api.invoke('planMove',{file:opened.value!.file,to});openModal('moveConfirm')}catch(e:any){modalError.value=e.message}}
async function movePost(){try{const doc=await api.invoke<DocumentFile>('move',movePlan.value);await refresh();opened.value=doc;raw.value=doc.raw;savedRaw.value=doc.raw;modal.value='';toast('文章已移动，已识别的引用已更新')}catch(e:any){modalError.value=e.message}}
async function trash(){try{if(dirty.value)throw new Error('请先保存或放弃当前修改');await api.invoke('trash',{file:opened.value!.file,hash:opened.value!.hash});opened.value=undefined;selected.value=undefined;raw.value='';savedRaw.value='';view.value='library';modal.value='';await refresh();toast('文章已移入系统回收站')}catch(e:any){modalError.value=e.message}}
async function recover(item:Recovery){try{let doc:DocumentFile;try{doc=await api.invoke('read',{file:item.file})}catch{doc={file:item.file,raw:'',hash:item.hash}}opened.value={...doc,hash:item.hash};savedRaw.value=doc.raw;raw.value=item.raw;view.value='write';modal.value='';fullSource.value=false;toast('恢复内容已进入编辑器，保存后才会写入原文件')}catch(e:any){modalError.value=e.message}}
async function discardRecovery(item:Recovery){await api.invoke('discardRecovery',{file:item.file});recoveries.value=recoveries.value.filter(r=>r!==item);if(!recoveries.value.length)closeModal()}
function quick(){quickQuery.value='';quickIndex.value=0;openModal('quick')}
function onKey(event:KeyboardEvent){if((event.ctrlKey||event.metaKey)&&!event.isComposing){if(event.key.toLowerCase()==='s'){event.preventDefault();if(view.value==='blog')void blogSettings.value?.save();else void save()}if(event.key.toLowerCase()==='p'){event.preventDefault();if(project.value)quick()}if(event.key.toLowerCase()==='n'){event.preventDefault();if(project.value)void protect(async()=>showNew())}}}
function resize(event:PointerEvent){const parent=(event.currentTarget as HTMLElement).parentElement!;const rect=parent.getBoundingClientRect();const move=(e:PointerEvent)=>{preferences.value.split=Math.min(70,Math.max(30,(e.clientX-rect.left)/rect.width*100))};const up=()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);void savePreferences()};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up)}
async function savePreferences(){await api.invoke('setPreferences',{...preferences.value,fontSize:fontSize.value,library:{category:category.value,query:query.value,year:year.value,month:month.value,tags:tags.value,sort:sort.value,selected:selected.value?.file,scroll:listTop.value}})}
function setTheme(value:'system'|'light'|'dark'){preferences.value.theme=value;void savePreferences()}
watch(query,()=>{if(composing.value)return;clearTimeout(searchTimer);searchTimer=setTimeout(()=>{search.value=query.value;listTop.value=0},200)})
watch(year,()=>month.value='')
watch(mode,()=>nextTick(sendPreview))
watch(quickQuery,()=>quickIndex.value=0)
watch(raw,()=>{++renderToken;scheduleRender();clearTimeout(recoveryTimer);if(dirty.value)recoveryTimer=setTimeout(()=>void persistRecovery().catch(()=>toast('恢复副本写入失败，请及时保存')),500)})
watch(dark,value=>{document.documentElement.classList.toggle('dark',value);sendPreview();sendOverview()},{immediate:true})
watch(()=>project.value?.styles,()=>{sendPreview();sendOverview()})
watch(view,()=>{if(view.value==='write'){previewReady.value=false;nextTick(sendPreview)}if(view.value==='library')nextTick(()=>{if(listScroller.value)listScroller.value.scrollTop=listTop.value})})
let preferencesTimer:ReturnType<typeof setTimeout>
watch([category,search,year,month,tags,sort,selected,listTop,fontSize],()=>{clearTimeout(preferencesTimer);preferencesTimer=setTimeout(()=>{if(project.value)void savePreferences().catch(()=>{})},400)},{deep:true})
function listArrow(index:number,direction:number){const next=Math.max(0,Math.min(filtered.value.length-1,index+direction));selected.value=filtered.value[next];const scroller=listScroller.value;if(scroller){if(next*rowStride<scroller.scrollTop)scroller.scrollTop=next*rowStride;else if((next+1)*rowStride>scroller.scrollTop+scroller.clientHeight)scroller.scrollTop=(next+1)*rowStride-scroller.clientHeight;listTop.value=scroller.scrollTop;nextTick(()=>scroller.querySelector<HTMLButtonElement>('.article-row.selected')?.focus())}}
async function externalChange(event:{kind:string;file?:string}){try{await refresh();if(event.kind!=='content'){sendPreview();return}if(!opened.value||event.file!==opened.value.file||saving.value)return;try{const doc=await api.invoke<DocumentFile>('read',{file:opened.value.file});if(doc.hash===opened.value.hash)return;if(dirty.value){disk.value=doc;openModal('conflict')}else{opened.value=doc;raw.value=doc.raw;savedRaw.value=doc.raw;toast('已同步外部修改')}}catch{toast('当前文件被移动或删除，仍可另存编辑内容')}}catch(e:any){toast(e.message)}}
const media=matchMedia('(prefers-color-scheme: dark)');const mediaChange=(event:MediaQueryListEvent)=>systemDark.value=event.matches
onMounted(async()=>{
  window.addEventListener('keydown',onKey);window.addEventListener('message',onMessage);media.addEventListener('change',mediaChange)
  if(!api){connectError.value='请通过桌面应用启动，以访问本地项目。';return}
  preferences.value={...preferences.value,...await api.invoke<Preferences>('preferences')};fontSize.value=preferences.value.fontSize||14
  stopChange=api.onChange(externalChange);stopClose=api.onClose(()=>void protect(async()=>{await persistRecovery();await api.invoke('close')}))
  if(preferences.value.project){pathInput.value=preferences.value.project;await connect();if(checked.value)enter()}
})
onBeforeUnmount(()=>{stopChange?.();stopClose?.();window.removeEventListener('keydown',onKey);window.removeEventListener('message',onMessage);media.removeEventListener('change',mediaChange);clearTimeout(searchTimer);clearTimeout(renderTimer);clearTimeout(recoveryTimer);clearTimeout(preferencesTimer)})
</script>

<template>
  <div class="app-shell">
    <WindowBar :path="project ? project.name + ' › ' + (opened?.file || 'posts') : 'Thus.Live › posts'" :read-only="project?.readOnly" />
    <main v-if="!connected" class="onboarding">
      <section class="connect-card" :class="{'connection-result':checked||connectError}">
        <p class="eyebrow">{{ checked||connectError?'项目连接':'THUS.LIVE EDITOR' }}</p>
        <h1>{{ connecting?'正在检查项目…':checked?'项目已就绪':connectError?'找不到这个项目目录':'从你的项目，开始写作。' }}</h1>
        <template v-if="!checked">
          <p class="intro">{{ connecting?'读取文章目录和渲染配置，完成后即可进入。':'连接本地目录，沿用博客的样式与排版。' }}</p>
          <button class="primary connect-primary" @click="chooseFolder" :disabled="connecting||!api">{{ connecting?'正在检查项目…':'选择项目目录' }}</button>
          <p class="intro"><button class="path-toggle" @click="pathExpanded=!pathExpanded">也可以粘贴项目的绝对路径。</button><br>支持 macOS、Windows 和 Linux。</p>
          <div v-if="pathExpanded||connectError" class="path-entry"><label for="project-path">项目目录<input id="project-path" v-model="pathInput" placeholder="选择 Thus.Live 项目根目录" @keydown.enter="connect" :disabled="connecting"></label><button @click="connect" :disabled="!pathInput||connecting||!api">连接目录</button></div>
          <p v-if="connectError" class="error" role="alert">{{ connectError }}</p>
        </template>
        <template v-else>
          <label>项目目录<p class="connection-path">{{ project?.root }}</p></label>
          <div class="connection-checks"><p>✓ 文章目录　content/posts/</p><p>{{ project?.warnings.length?'!':'✓' }} 文章样式　{{ project?.warnings.length?'需要检查':'theme.css + markdown.css' }}</p><p>✓ 渲染配置　VitePress · 扩展语法</p><p>✓ 日期规则　YYYY / MM / DD</p></div>
          <p v-for="warning in project?.warnings" class="warning">{{ warning }}</p>
          <div class="actions"><button class="primary" @click="enter">{{ project?.warnings.length?'使用可用样式进入':'进入写作空间' }}</button><button @click="checked=false;project=undefined">重新选择</button></div>
        </template>
      </section>
    </main>
    <div v-else class="workspace">
      <nav class="sidebar" aria-label="主导航"><div class="brand">Thus.Live /</div><button class="primary" @click="protect(async()=>showNew())">＋ 新建文章</button><div class="nav-items"><button :class="{active:view==='blog'}" @click="view='blog'">博客信息</button><button :class="{active:view==='write'&&isHome}" @click="load('index.md')">首页信息</button><button v-for="item in [{id:'all',name:'全部文章'},{id:'drafts',name:'草稿'}]" :class="{active:category===item.id&&(view==='library'||(view==='write'&&!isHome))}" @click="navigate(item.id)"><span>{{ item.name }}</span></button></div><div class="nav-bottom"><button :class="{active:view==='settings'}" @click="view='settings'">项目设置</button></div></nav>
      <section v-if="view==='library'" class="library">
        <div class="article-list"><div class="list-head"><h2>{{ ({all:'全部文章',drafts:'草稿',tags:'标签筛选',archive:'日期归档'} as any)[category] }}<span v-if="category!=='all'" class="list-count"> · {{ filtered.length }}</span></h2>
          <input v-model="query" aria-label="搜索文章" placeholder="搜索标题、文件名或标签" @compositionstart="composing=true" @compositionend="composing=false;search=query">
          <button class="sort-button ghost" aria-label="文章排序" @click="sort=sort==='modified'?'date':'modified'">{{ sort==='modified'?'最近修改':'发布日期' }} ↓</button>
          <div class="filters"><button @click="openModal('date')">{{ year||'全部年份' }}</button><button @click="openModal('date')">{{ month?Number(month)+' 月':'全部月份' }}</button><button @click="tagQuery='';openModal('tags')">{{ tags.length?tags.length+' 个标签':'选择标签' }}</button></div>
          <button class="clear-filter" v-if="search||year||month||tags.length" @click="query='';search='';year='';month='';tags=[]">清除筛选</button></div>
          <div ref="listScroller" class="list-scroll" @scroll="listTop=($event.target as HTMLElement).scrollTop" role="list" aria-label="文章列表"><div :style="{height:filtered.length*rowStride+'px',position:'relative'}"><button v-for="(post,index) in visiblePosts" :key="post.file" class="article-row" :class="{selected:selected?.file===post.file}" :style="{top:(virtualStart+index)*rowStride+'px'}" @click="selected=post" @dblclick="load(post)" @keydown.enter="load(post)" @keydown.down.prevent="listArrow(virtualStart+index,1)" @keydown.up.prevent="listArrow(virtualStart+index,-1)"><span class="row-title">{{ post.title }}</span><span class="row-description">{{ post.description }}</span><span class="row-meta">{{ post.date }} · {{ post.draft?'草稿':'非草稿' }}<span v-if="post.error" class="error"> · 元信息待修复</span></span></button></div><div v-if="!filtered.length" class="empty"><span class="empty-symbol">/</span><h3>{{ posts.length?'没有找到匹配的文章':'写下第一段文字' }}</h3><p>{{ posts.length?'试试其他关键词，或清除筛选条件。':'从一篇草稿开始，把想法留在这里。' }}</p><button v-if="!posts.length" class="primary" @click="showNew">新建文章</button></div></div>
        </div>
        <div class="overview" v-if="selected"><button class="primary" @click="load(selected)">开始写作 →</button><p v-if="overviewError" class="error">{{ overviewError }}<button @click="renderOverview">重试预览</button></p><div class="overview-preview"><div v-if="overviewLoading" class="rendering">正在更新预览…</div><iframe ref="overviewPreview" src="./preview.html" sandbox="allow-scripts" title="文章概览预览" @load="sendOverview"></iframe></div></div>
        <div v-else class="overview overview-empty"><h1>{{ posts.length?'没有匹配的文章。':'让想法有一个起点。' }}</h1></div>
      </section>
      <section v-else-if="view==='write'&&opened" class="writing">
        <div class="toolbar"><button @click="quick">文章 <kbd>{{ modifier }} P</kbd></button><div class="view-switch"><button v-for="item in [{id:'write',label:'写作'},{id:'split',label:'分栏'},{id:'preview',label:'预览'}]" :class="{active:mode===item.id}" @click="mode=item.id as any">{{ item.label }}</button></div><div class="article-actions"><button v-if="!isHome" class="ghost" @click="showMetadata">文章信息</button><button v-else class="ghost" @click="fullSource=!fullSource">{{ fullSource?'编辑正文':'完整源码' }}</button><button class="ghost" @click="chooseImage()">插入图片</button><button class="primary" @click="save" :disabled="saving||!dirty||project?.readOnly">{{ saving?'保存中…':'保存' }}</button><button class="more" aria-label="更多文章操作" @click="openModal('more')"><svg width="20" height="20" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true"><circle cx="4" cy="10" r="1.5"/><circle cx="10" cy="10" r="1.5"/><circle cx="16" cy="10" r="1.5"/></svg></button></div></div>
        <div v-if="saveError||renderError||yamlError" class="error-strip" role="alert">{{ yamlError||saveError||(renderError+' · 仍显示上次成功预览') }}<button v-if="renderError" @click="runRender">重试预览</button><button v-if="yamlError" @click="fullSource=true">编辑完整源码</button></div>
        <div class="panes" :class="mode" :style="{'--split':(preferences.split||50)+'%'}"><div v-show="mode!=='preview'" class="editor-pane"><div class="editor-heading" :class="{'source-heading':fullSource}"><template v-if="fullSource"><h2>完整源文件</h2><p class="help">元信息与正文 · 保留未知字段 <button class="ghost" @click="fullSource=false">返回正文</button></p></template><template v-else><div class="eyebrow">{{ isHome?'首页 MARKDOWN':'MARKDOWN' }}<button v-if="!isHome" @click="showMetadata">文章信息</button></div><h1>{{ activeTitle }}</h1><div v-if="isHome" class="editor-meta">content/index.md · 首页正文与元信息</div><div v-else class="editor-meta">{{ currentPost?.date }}　 ·　 {{ metadata.draft===true?'草稿':'非草稿' }}　 ·　 {{ (metadata.tags||[]).join(' / ') }}</div></template></div><Editor ref="editor" v-model="editorText" :doc-key="opened.file+(fullSource?':raw':':body')" :dark="dark" :font-size="fontSize" @scroll="onEditorScroll" @image="droppedImage" /></div><div v-if="mode==='split'" class="divider" role="separator" aria-label="调整编辑与预览宽度" tabindex="0" @pointerdown.prevent="resize" @keydown.left.prevent="preferences.split=Math.max(30,(preferences.split||50)-2)" @keydown.right.prevent="preferences.split=Math.min(70,(preferences.split||50)+2)"></div><div v-show="mode!=='write'" class="preview-pane"><div v-if="rendering" class="rendering">正在更新预览…</div><iframe ref="preview" src="./preview.html" sandbox="allow-scripts" title="文章实时预览" @load="sendPreview"></iframe></div></div>
      </section>
      <section v-else-if="view==='settings'" class="settings">
        <nav class="settings-nav" aria-label="设置分类"><h2>设置</h2><button v-for="item in [{id:'project',name:'项目'},{id:'render',name:'渲染兼容性'},{id:'appearance',name:'外观与写作'},{id:'shortcuts',name:'快捷键'}]" :class="{active:settingsTab===item.id}" @click="settingsTab=item.id">{{ item.name }}</button><button v-if="opened" class="back-to-editor" @click="view='write'">返回写作</button></nav>
        <div class="settings-content">
          <template v-if="settingsTab==='project'"><h1>项目设置</h1><p class="intro">当前项目的目录与内容约定。切换项目不影响原目录。</p><label>项目目录<input readonly :value="project?.root"></label><label>文章目录<input readonly value="content/posts/"></label><label>日期与新建规则<input readonly :value="Intl.DateTimeFormat().resolvedOptions().timeZone+' · YYYY/MM/DD/slug.md'"></label><p class="help">最近项目由应用保存。切换前先处理未保存内容。</p><div class="actions"><button class="primary" @click="protect(async()=>{project=undefined;opened=undefined;selected=undefined;raw='';savedRaw='';checked=false})">切换项目</button><button class="ghost" @click="refresh().then(()=>toast('项目已重新读取')).catch(e=>toast(e.message))">重新检测</button><button class="ghost" @click="api.invoke<Recovery[]>('recoveries').then(items=>{recoveries=items;openModal('recovery')})">恢复副本</button></div></template>
          <template v-else-if="settingsTab==='render'"><h1>{{ renderError?'预览加载失败':'渲染兼容性' }}</h1><p class="intro">读取项目样式，并校验扩展语法的实际渲染结果。</p><label>主题与正文<div class="setting-value">{{ project?.warnings.length?'需要检查':'已读取' }} · theme.css + markdown.css</div></label><label>代码与图表<div class="setting-value">Shiki 双主题 · 代码组 · MathJax · Mermaid</div></label><label>Markdown 扩展<div class="setting-value">提示容器 · 脚注 · 任务列表 · 定义 · 缩写 · Emoji<br>高亮 · 上下标 · 标题去重 · 二三级目录</div></label><p class="help">{{ renderError?'预览加载失败；正文仍可编辑。':renderResult||overviewResult?'当前文章已完成渲染。':'打开文章后检查实际预览效果。' }}</p><p v-if="renderError" class="error">{{ renderError }}</p><p v-for="warning in project?.warnings" class="warning">{{ warning }}</p><button class="primary" @click="opened?runRender():renderOverview()">重新检查</button></template>
          <template v-else-if="settingsTab==='appearance'"><h1>外观与写作</h1><p class="intro">让编辑环境适合你的阅读习惯。</p><div class="setting-field"><p class="field-label">主题</p><div class="theme-options" role="group" aria-label="颜色主题"><button v-for="item in [{id:'light',label:'浅色'},{id:'dark',label:'深色'},{id:'system',label:'跟随系统'}]" :class="{active:preferences.theme===item.id}" @click="setTheme(item.id as any)">{{ item.label }}</button></div></div><label>编辑字号<select v-model.number="fontSize"><option :value="14">14 px</option><option :value="16">16 px</option><option :value="18">18 px</option></select></label><label>同步滚动<select v-model="preferences.syncScroll" @change="savePreferences"><option :value="true">开启 · 按源码位置同步</option><option :value="false">关闭</option></select></label><p class="help">只影响编辑器；文章预览沿用项目字体与排版。减少动态效果跟随系统。</p></template>
          <template v-else><h1>快捷键</h1><p class="intro">macOS 使用 ⌘，Windows 和 Linux 使用 Ctrl。</p><label>文章操作<div class="setting-value shortcut-list"><span>保存 <kbd>{{ modifier }} + S</kbd></span><span>快速打开 <kbd>{{ modifier }} + P</kbd></span><span>新建文章 <kbd>{{ modifier }} + N</kbd></span></div></label><label>编辑操作<div class="setting-value shortcut-list"><span>撤销 <kbd>{{ modifier }} + Z</kbd></span><span>重做 <kbd>{{ modifier }} + Shift + Z</kbd></span><span>查找 <kbd>{{ modifier }} + F</kbd></span></div></label><label>导航<div class="setting-value">↑ ↓ 选择文章　 Enter 打开　 Esc 关闭弹窗</div></label><p class="help">快捷键在输入法合成期间不误触发；不覆盖系统保留组合。</p></template>
        </div>
      </section>
      <BlogSettings v-if="project" :key="project.root" ref="blogSettings" :visible="view==='blog'" :read-only="project.readOnly" />
    </div>
    <footer class="statusbar"><span :class="{error:saveError}">{{ saving?'● 保存中':dirty?'● 有未保存修改':opened?'● 已保存到本地':project?'● 本地工作空间':'尚未连接项目' }}</span><span>{{ project?.warnings.length?'预览兼容性需检查':project?'项目样式已同步':'' }}</span><span>UTF-8　 Markdown</span></footer>
    <div v-if="notice" class="toast" role="status">{{ notice }}</div>

    <Modal v-if="modal" :key="modal" :kind="modal" :title="modal==='new'&&modalError.includes('存在')?'文件名已存在':({new:'新建文章',metadata:'文章信息',publish:'将文章设为非草稿？',date:'按日期筛选',tags:'选择标签',quick:'快速打开文章',unsaved:'保存修改后再离开？',conflict:'文件已在其他程序中修改',saveError:'保存失败，内容仍在',image:'插入图片',imageConflict:'图片文件同名',move:'移动或重命名文章',moveConfirm:'确认移动影响',trash:'移入回收站？',more:'文章操作',recovery:'恢复未保存内容',yaml:'元信息格式需要修复',external:'在浏览器打开链接？'} as any)[modal]" @close="closeModal">
      <template v-if="modal==='new'||modal==='move'"><p class="help">{{ modal==='new'?'新文章默认为草稿，不参与站点构建。':'移动前会检查目标路径与项目内引用。' }}</p><label v-if="modal==='new'">标题<input v-model="forms.title" autofocus placeholder="文章标题"></label><label>文件名<input v-model="forms.slug" placeholder="my-new-post"></label><div class="form-grid"><label>发布日期<input type="date" v-model="forms.date"></label><label>文件方式<select v-model="forms.folder" aria-label="文件方式"><option :value="false">slug.md</option><option :value="true">slug/index.md</option></select></label></div><p class="path">content/posts/{{ forms.date?.replaceAll('-','/') }}/{{ forms.slug||'slug' }}{{ forms.folder?'/index':'' }}.md</p><div class="actions"><button class="primary" @click="modal==='new'?createPost():planMove()">{{ modal==='new'?'创建草稿':'检查移动影响' }}</button><button @click="closeModal">取消</button></div></template>
      <template v-else-if="modal==='metadata'"><p class="help">标题、摘要与标签同步到 Markdown 元信息，未知字段保留。</p><label>标题<input v-model="forms.title" autofocus></label><label>摘要<input v-model="forms.description"></label><label>标签<input v-model="forms.tags" placeholder="用逗号分隔"></label><div class="form-grid"><label>文章状态<select v-model="forms.draft" aria-label="文章状态"><option :value="true">草稿</option><option :value="false">非草稿</option></select></label><label>更新日期（可选）<input v-model="forms.updated" type="date"></label></div><p class="help">发布日期来自目录。应用修改后，仍需保存文章。</p><div class="actions"><button class="primary" @click="applyMetadata()">应用修改</button><button @click="closeModal">取消</button></div></template>
      <template v-else-if="modal==='publish'"><p>设为非草稿并保存后，这篇文章会参与下次站点构建。此操作不会自动构建或部署。</p><div class="actions"><button class="primary" @click="applyMetadata(true)">确认设为非草稿</button><button @click="openModal('metadata')">返回</button></div></template>
      <template v-else-if="modal==='date'"><p class="field-label">年份</p><div class="year-options" role="group" aria-label="年份"><button :class="{active:!filterYear}" :aria-pressed="!filterYear" @click="filterYear='';filterMonth=''">全部年份</button><button v-for="y in years" :key="y" :class="{active:filterYear===y}" :aria-pressed="filterYear===y" @click="filterYear=y;filterMonth=''">{{ y }}</button></div><div class="month-grid"><button :class="{active:!filterMonth}" @click="filterMonth=''">全年</button><button v-for="m in 12" :key="m" :class="{active:filterMonth===String(m).padStart(2,'0')}" @click="filterMonth=String(m).padStart(2,'0')">{{ m }} 月 <small>{{ posts.filter(p=>(!filterYear||p.date.startsWith(filterYear))&&p.date.slice(5,7)===String(m).padStart(2,'0')).length }}</small></button></div><div class="actions"><button class="primary" @click="applyFilters">查看文章</button><button @click="closeModal">取消</button></div></template>
      <template v-else-if="modal==='tags'"><label>搜索标签<input v-model="tagQuery" placeholder="搜索已有标签"></label><p class="help">匹配任意所选标签；标签条件与日期、关键词取交集。</p><div class="tag-picker"><label v-for="tag in allTags.filter(t=>t.includes(tagQuery))" :key="tag"><input type="checkbox" :value="tag" v-model="filterTags">{{ tag }}<span class="muted">{{ posts.filter(p=>p.tags.includes(tag)).length }}</span></label></div><div class="actions"><button class="primary" @click="applyFilters">查看文章</button><button @click="filterTags=[]">清除</button><button @click="closeModal">取消</button></div></template>
      <template v-else-if="modal==='quick'"><p>按标题、文件名或标签查找。</p><input autofocus v-model="quickQuery" placeholder="搜索标题、标签或文件名" aria-label="快速查找" @keydown.down.prevent="quickIndex=Math.min(quickResults.length-1,quickIndex+1)" @keydown.up.prevent="quickIndex=Math.max(0,quickIndex-1)" @keydown.enter.prevent="quickResults[quickIndex]&&load(quickResults[quickIndex])"><div class="quick-results"><button v-for="(post,i) in quickResults" :class="{active:i===quickIndex}" @click="load(post)"><span>{{ post.title }}</span><small>{{ post.date }} · {{ post.draft?'草稿':'非草稿' }}</small></button><p v-if="!quickResults.length" class="help">没有匹配的文章</p></div><p class="help">↑ ↓ 选择 · Enter 打开 · Esc 返回</p></template>
      <template v-else-if="modal==='unsaved'"><p>「{{ activeTitle }}」还有未保存的修改。</p><label>将要离开<input readonly :value="opened?.file"></label><p class="help">放弃后会保留恢复副本，原文件不会写入。</p><div class="actions"><button class="primary" :disabled="saving" @click="continueUnsaved()">保存并继续</button><button class="danger" @click="continueUnsaved(true)">放弃修改</button><button @click="closeModal">取消</button></div></template>
      <template v-else-if="modal==='conflict'"><p>为避免覆盖外部修改，已暂停保存。可以另存当前内容，或重新加载磁盘版本。</p><div class="comparison"><div><h3>当前编辑内容</h3><pre>{{ raw }}</pre></div><div><h3>磁盘版本</h3><pre>{{ disk?.raw||'文件已不可读' }}</pre></div></div><p class="help">重新加载将舍弃当前缓冲区，应用会先保留恢复副本。</p><div class="actions"><button class="primary" @click="saveAs">另存当前内容</button><button @click="reloadDisk">重新加载磁盘</button><button @click="closeModal">取消</button></div></template>
      <template v-else-if="modal==='saveError'"><p class="error">{{ saveError }}</p><label>目标文件<input readonly :value="opened?.file"></label><p class="help">编辑内容仍保留在窗口中。</p><div class="actions"><button class="primary" @click="save().then(ok=>{if(ok)closeModal()})">重试保存</button><button @click="saveAs">另存副本</button><button @click="closeModal">返回编辑</button></div></template>
      <template v-else-if="modal==='image'&&imageData"><p>从本地选择图片，复制到文章附近的 assets 目录。</p><label>图片文件<input readonly :value="imageData.name + ' · ' + (imageData.bytes.length/1024).toFixed(1) + ' KB'"></label><label>替代文字<input v-model="imageData.alt" autofocus placeholder="描述图片内容"></label><label>插入路径<input readonly :value="'./assets/'+imageData.name"></label><p class="help">遇到同名文件，默认自动编号保留两份，不覆盖原图。</p><div class="actions"><button class="primary" @click="insertImage()">复制并插入</button><button @click="closeModal">取消</button></div></template>
      <template v-else-if="modal==='imageConflict'&&plannedImage"><p>assets 目录中已有同名图片。</p><label>现有文件<input readonly :value="plannedImage.original"></label><label>建议新文件名<input readonly :value="plannedImage.suggested"></label><p class="help">默认保留两份。可以返回重新选择，或使用现有图片。</p><div class="actions"><button class="primary" @click="insertImage(false,true)">保留两份</button><button @click="insertImage(true,true)">使用现有图片</button><button @click="openModal('image')">返回</button></div></template>
      <template v-else-if="modal==='moveConfirm'&&movePlan"><p>检查完成后，再执行文件移动。</p><label>原路径<input readonly :value="movePlan.from"></label><label>目标路径<input readonly :value="movePlan.to"></label><label>引用检查<input readonly :value="`将更新 ${movePlan.references.length} 篇文章中的可识别链接。`"></label><ul v-if="movePlan.references.length"><li v-for="file in movePlan.references" :key="file">{{ file }}</li></ul><p class="help">{{ movePlan.warning }}</p><div class="actions"><button class="primary" @click="movePost">确认移动</button><button @click="openModal('move')">返回</button></div></template>
      <template v-else-if="modal==='trash'"><p>文章将从当前项目移除，可以从系统回收站恢复。</p><label>文章<input readonly :value="activeTitle"></label><p class="help">其他文章中的链接可能失效。共享附件会保留；不会永久删除。</p><div class="actions"><button class="danger" @click="trash">移入回收站</button><button @click="closeModal">取消</button></div></template>
      <template v-else-if="modal==='more'"><p>{{ activeTitle }}</p><div class="menu-list"><button @click="fullSource=!fullSource;closeModal()">{{ fullSource?'编辑正文':'编辑完整源文件' }}</button><button v-if="!isHome" @click="showMove">移动或重命名</button><button @click="saveAs">另存副本</button><button v-if="!isHome" @click="openModal('trash')" class="danger">移入回收站</button><button @click="closeModal();navigate('all')">返回文章库</button></div></template>
      <template v-else-if="modal==='recovery'"><p>恢复副本不会自动覆盖原文件，打开后请检查并保存。</p><div v-for="item in recoveries" class="recovery-row"><div><strong>{{ item.file }}</strong><small>{{ new Date(item.time).toLocaleString() }}</small></div><button class="primary" @click="recover(item)">恢复</button><button @click="discardRecovery(item)">删除副本</button></div><p v-if="!recoveries.length" class="help">暂无恢复副本。</p></template>
      <template v-else-if="modal==='yaml'"><pre class="error">{{ yamlError }}</pre><p>原始内容已保留。请在完整源码中修复 YAML 后，再编辑文章信息。</p><button class="primary" @click="fullSource=true;closeModal()">编辑完整源码</button></template>
      <template v-else-if="modal==='external'"><p class="path">{{ forms.url }}</p><div class="actions"><button class="primary" @click="api.invoke('external',{url:forms.url});closeModal()">在浏览器打开</button><button @click="closeModal">取消</button></div></template>
      <p v-if="modalError" class="error" role="alert">{{ modalError }}</p>
    </Modal>
  </div>
</template>
